title: Projects
author: Cinthya Cabanzo

description: > # this means to ignore newlines until "baseurl:"
  Here you can find the projects developed related with the courses at Platzi.
  
  Uber:
  Bank Cyn:
  


# social links
hackerrank:@cinthya_cabanzo
github_username:  cinthylli

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
